import { AnimatedGradientBackground } from '@/components/AnimatedGradientBackground';
import { ScrollReveal } from '@/components/ScrollReveal';
import Link from 'next/link';

const articles = [
  {
    title: "The Rise of Private AI: Why Your Browser Is the New Cloud",
    excerpt: "How WebLLM and distributed nodes are changing the AI landscape – no data centres, total privacy.",
    date: "June 2025",
    readTime: "5 min",
    slug: "rise-of-private-ai",
  },
  {
    title: "Programmatic SEO at Scale: A Case Study",
    excerpt: "How we used KI to generate 10,000 landing pages and increase organic traffic by 400%.",
    date: "May 2025",
    readTime: "4 min",
    slug: "programmatic-seo-case-study",
  },
  {
    title: "Building a DeepSeek‑like Chatbot with WebLLM",
    excerpt: "Step‑by‑step guide to creating a private, local AI assistant using only browser technologies.",
    date: "April 2025",
    readTime: "7 min",
    slug: "deepseek-like-chatbot-webllm",
  },
  {
    title: "Why GMB SEO Is Still the Best ROI for Local Businesses",
    excerpt: "Case studies and data proving Google Maps optimisation delivers 10x returns.",
    date: "March 2025",
    readTime: "6 min",
    slug: "gmb-seo-roi",
  },
  {
    title: "Automating Instagram Reels with AI – Our Viral Formula",
    excerpt: "The exact prompt and strategy we use to guarantee 2 viral posts per month.",
    date: "February 2025",
    readTime: "8 min",
    slug: "instagram-viral-automation",
  },
  {
    title: "Open Source vs Proprietary AI: The Kalki Manifesto",
    excerpt: "Why we believe AI should be free, private, and owned by the people.",
    date: "January 2025",
    readTime: "10 min",
    slug: "open-source-ai-manifesto",
  },
];

export default function BlogPage() {
  return (
    <>
      <AnimatedGradientBackground />
      <div className="relative z-10 pt-28 pb-20 px-4 md:px-8">
        <div className="max-w-7xl mx-auto">
          <ScrollReveal>
            <div className="text-center mb-12">
              <h1 className="text-5xl md:text-6xl font-serif mb-3">KI Blog</h1>
              <p className="text-gray-400 max-w-2xl mx-auto">
                Insights on private AI, digital marketing, WebLLM, and the future of distributed intelligence.
              </p>
            </div>
          </ScrollReveal>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {articles.map((article, idx) => (
              <ScrollReveal key={article.slug} delay={idx * 0.05}>
                <div className="glass-card rounded-2xl p-6 hover:scale-105 transition-all duration-300 h-full flex flex-col">
                  <div className="flex items-center gap-2 text-xs text-gray-500 mb-3">
                    <span>{article.date}</span>
                    <span>•</span>
                    <span>{article.readTime}</span>
                  </div>
                  <h3 className="text-xl font-serif font-semibold mb-2">{article.title}</h3>
                  <p className="text-gray-400 text-sm flex-1">{article.excerpt}</p>
                  <div className="mt-4">
                    <Link href={`/blog/${article.slug}`} className="text-gold-400 text-sm inline-flex items-center gap-1 hover:gap-2 transition-all">
                      Read more →
                    </Link>
                  </div>
                </div>
              </ScrollReveal>
            ))}
          </div>
          <div className="text-center mt-16 text-gray-400 text-sm">
            <p>All articles are generated by KI and reviewed by humans – 100% original content.</p>
          </div>
        </div>
      </div>
    </>
  );
}
